### ISSUE TITLE
Informações na Documentação

### ISSUE THREAD

**Issue by Valerianofilipec** [gcamposl/ignite-template-introducao-ao-SOLID#1]
Boas Gabriel, 

Muito massa a sua ideia de reservar um tempo para documentar o que é praticado/estudado. 
Quero deixar aqui apenas sugestão de adicionar mais algumas informações (para este e futuros projetos) como um breve resumo/introdução do problema/projeto (sugiro usares o método S.T.A.R.)  e um tutorial de como correr a aplicação/projeto. Creio que com essas informções deixaria outros devs/recrutadores mais a par do que  está a ser
feito e como.

Sem mais acrescentar, desejo-lhe um bom aproveito ao percurso no Ignite (colega).
Valeriano Filipe

**Comment by gcamposl** [comment]
Muito obrigado Valeriano Felipe, pela sugestão! Vou segui-la a risca nas
próximas publicações!

Em qui., 10 de fev. de 2022 às 07:29, Valeriano Filipe <
***@***.***> escreveu:
